### ISSUE TITLE
카테고리에서 "기타"를 선택할 수 없어요

### ISSUE THREAD

**Issue by Combi153** [woowacourse-teams/2023-3-ddang#221]
### 🐞 설명

글 등록할 때 상품 카테고리를 "기타"로 하려고 했는데 안 돼요

### 📄 기대한 동작

기타 선택하면 넘어갈 줄 알았어요

### 📄 실제 동작

넘어가지 않고 선택할 항목도 없네요

### 🙋🏻 재현 방법

상품 등록할 때 카테고리 선택에서 맨 밑에 기타를 선택해요

### 🌏 버그 발생 환경

휴대폰

**Comment by apptie** [comment]
@Combi153 감사합니다 덕분에 문제를 수정할 수 있었습니다
