### ISSUE TITLE
상품 카테고리에서 다른 카테고리에서 기타 카테고리로 넘어가는 게 가능해요

### ISSUE THREAD

**Issue by Combi153** [woowacourse-teams/2023-3-ddang#224]
### 🐞 설명

다른 카테고리 눌렀다가 기타 누르면 다른 카테고리의 항목들이 떠요.
눌러서 선택하면 "기타>피규어/프라모델..." 이런 게 가능해져요

### 📄 기대한 동작

![KakaoTalk_Photo_2023-08-07-14-16-08 002](https://github.com/woowacourse-teams/2023-3-ddang/assets/106813090/f90abdf1-2240-48d5-a33b-0f2f90708996)

기타 누르면 다른 카테고리의 항목이 안 보여야 할 것 같아요

### 📄 실제 동작

![KakaoTalk_Photo_2023-08-07-14-16-38](https://github.com/woowacourse-teams/2023-3-ddang/assets/106813090/76204451-cad5-44c1-b4d0-0ecaddfccf57)
![KakaoTalk_Photo_2023-08-07-14-16-08 001](https://github.com/woowacourse-teams/2023-3-ddang/assets/106813090/fada5576-226a-4bc8-a78b-e1a06ebe1853)

### 🙋🏻 재현 방법

다른 카테고리 눌렀다가 기타 카테고리 선택하기

**Comment by hyemdooly** [comment]
백엔드에서 기타-기타 항목을 추가하여 처리해주셨습니다~ 버그 리포팅 감사합니다. :)
