### ISSUE TITLE
로그인 안 한 경우 경매 상세 조회 불가한 오류 수정

### ISSUE THREAD

**Issue by swonny** [woowacourse-teams/2023-3-ddang#319]
### 🐞 설명

로그인 안 한 경우 경매 상세 조회 불가한 오류 수정

### 🌏 버그 발생 환경

mac

### ⏰ 추정 시간

30분

### ⏰ 소요 시간

30분

**Comment by apptie** [comment]
정책 변경으로 인해 반영하지 않고 close하도록 하겠습니다
