### ISSUE TITLE
PR 코드 분석 시 suggestion 태그를 위한 로직 추가

### ISSUE THREAD

**Issue by JJ503** [woowacourse-teams/2023-3-ddang#740]
### 🤔 설명

`suggestion` 태그의 경우 jacocoCoverageTest를 할 필요도 없고 그에 따른 결과도 보일 필요가 없다고 생각합니다.
또한, 제안인지 아닌지에 대해서도 슬랙에서 바로 보이는 것이 더 편할 것이라 생각해 해당 로직이 추가되기를 원해 제안해 봅니다.
멘션은 굳이 추가하지 않았는데, 제안의 경우 멘션이 바로 걸렸으면 한다는 의견이 있으면 논의 후 결과에 따라 진행하도록 하겠습니다.

### ✅ 작업할 내용

- [x] suggestion 태그에 대한 분기처리 추가
- [x] suggestion 태그를 위한 slack 메시지 추가

### ⏰ 추정 시간

30분

### ⏰ 소요 시간

약 2시간 30분

**Comment by apptie** [comment]
이 부분 있으면 좋을 것 같습니다 
지금 이것저것 하면서 필요성을 체감하고 있습니다

**Comment by apptie** [comment]
멘션은 전 바로 걸려도 괜찮을 것 같습니다
